deploy to staging and production repositories

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,6 +9,135 @@ commands:
             git config user.name "$GITHUB_USERNAME"
             git config user.email "$GITHUB_EMAIL"
 
+  deploy-rpm:
+    parameters:
+      username:
+        type: string
+      password:
+        type: string
+      serverurl:
+        type: string
+      repository-name:
+        type: string
+    steps:
+      - run:
+          name: Deploy .rpm to a Yum repository
+          command: |
+            echo "Running deploy-rpm: ${RPM_NAME} to: << parameters.serverurl >><< parameters.repository-name >>"
+            curl -v --user << parameters.username >>:<< parameters.password >> --upload-file build/${RPM_NAME} << parameters.serverurl >><< parameters.repository-name >>/
+            res=$?
+            if test "$res" != "0"; then
+              echo "the yum curl command failed with: $res"
+              exit 1
+            fi
+
+  deploy-rpm-staging:
+    parameters:
+      username:
+        type: string
+        default: $NEXUS_RM_USERNAME_YUM_STAGING
+      password:
+        type: string
+        default: $NEXUS_RM_PASSWORD_YUM_STAGING
+      serverurl:
+        type: string
+        default: $NEXUS_RM_SERVERURL_STAGING
+      repository-name:
+        type: string
+        default: $REPOSITORY_NAME_YUM_STAGING
+    steps:
+      - deploy-rpm:
+          username: << parameters.username >>
+          password: << parameters.password >>
+          serverurl: << parameters.serverurl >>
+          repository-name: << parameters.repository-name >>
+
+  deploy-rpm-production:
+    parameters:
+      username:
+        type: string
+        default: $NEXUS_RM_USERNAME_YUM_PRODUCTION
+      password:
+        type: string
+        default: $NEXUS_RM_PASSWORD_YUM_PRODUCTION
+      serverurl:
+        type: string
+        default: $NEXUS_RM_SERVERURL_PRODUCTION
+      repository-name:
+        type: string
+        default: $REPOSITORY_NAME_YUM_PRODUCTION
+    steps:
+      - deploy-rpm:
+          username: << parameters.username >>
+          password: << parameters.password >>
+          serverurl: << parameters.serverurl >>
+          repository-name: << parameters.repository-name >>
+
+  deploy-deb:
+    parameters:
+      username:
+        type: string
+      password:
+        type: string
+      serverurl:
+        type: string
+      repository-name:
+        type: string
+    steps:
+      - run:
+          name: Deploy .deb to an Apt repository
+          command: |
+            echo "Running deploy-deb: ${DEB_NAME} to: << parameters.serverurl >><< parameters.repository-name >>"
+            curl -v --user << parameters.username >>:<< parameters.password >> -H "Content-Type: multipart/form-data" --data-binary "@build/${DEB_NAME}" << parameters.serverurl >><< parameters.repository-name >>/
+            res=$?
+            if test "$res" != "0"; then
+              echo "the apt curl command failed with: $res"
+              exit 2
+            fi
+
+  deploy-deb-staging:
+    parameters:
+      username:
+        type: string
+        default: $NEXUS_RM_USERNAME_APT_STAGING
+      password:
+        type: string
+        default: $NEXUS_RM_PASSWORD_APT_STAGING
+      serverurl:
+        type: string
+        default: $NEXUS_RM_SERVERURL_STAGING
+      repository-name:
+        type: string
+        default: $REPOSITORY_NAME_APT_STAGING
+    steps:
+      - deploy-deb:
+          username: << parameters.username >>
+          password: << parameters.password >>
+          serverurl: << parameters.serverurl >>
+          repository-name: << parameters.repository-name >>
+
+  deploy-deb-production:
+    parameters:
+      username:
+        type: string
+        default: $NEXUS_RM_USERNAME_APT_PRODUCTION
+      password:
+        type: string
+        default: $NEXUS_RM_PASSWORD_APT_PRODUCTION
+      serverurl:
+        type: string
+        default: $NEXUS_RM_SERVERURL_PRODUCTION
+      repository-name:
+        type: string
+        default: $REPOSITORY_NAME_APT_PRODUCTION
+    steps:
+      - deploy-deb:
+          username: << parameters.username >>
+          password: << parameters.password >>
+          serverurl: << parameters.serverurl >>
+          repository-name: << parameters.repository-name >>
+
+
 jobs:
   build:
     docker:
@@ -59,19 +188,10 @@ jobs:
             echo export RPM_NAME="${RPM_NAME}" >> "$BASH_ENV"
             echo export DEB_NAME="${DEB_NAME}" >> "$BASH_ENV"
 
-            curl -v --user ${NEXUS_RM_USERNAME_YUM}:${NEXUS_RM_PASSWORD_YUM} --upload-file build/${RPM_NAME} ${NEXUS_RM_SERVERURL}${REPOSITORY_NAME_YUM}/
-            res=$?
-            if test "$res" != "0"; then
-              echo "the yum curl command failed with: $res"
-              exit 1
-            fi
-
-            curl -v --user ${NEXUS_RM_USERNAME_APT}:${NEXUS_RM_PASSWORD_APT} -H "Content-Type: multipart/form-data" --data-binary "@build/${DEB_NAME}" ${NEXUS_RM_SERVERURL}${REPOSITORY_NAME_APT}/
-            res=$?
-            if test "$res" != "0"; then
-              echo "the apt curl command failed with: $res"
-              exit 2
-            fi
+      - deploy-rpm-staging
+      - deploy-deb-staging
+      - deploy-rpm-production
+      - deploy-deb-production
 
   read_published_release_version:
     docker:
@@ -109,7 +229,7 @@ jobs:
             fi
 
 workflows:
-  manual_deploy_staging:
+  manual_deploy:
     jobs:
       - build
       - hold:
@@ -121,7 +241,7 @@ workflows:
               only:
                 - master
       - build_and_deploy:
-          context: installer-deploy-staging
+          context: installer-deploy
           requires:
             - hold
           filters:
@@ -153,7 +273,7 @@ workflows:
             tags:
               only: /.*/
       - build_and_deploy:
-          context: installer-deploy-staging
+          context: installer-deploy
           filters:
             # ignore any commit on any branch by default (branch and tag filters are ORed)
             branches:
